import icon1 from "./icons8-behance.svg";
import icon2 from "./icons8-credly.svg";
import icon3 from "./icons8-dribble.svg";
import icon4 from "./icons8-facebook.svg";
import icon5 from "./icons8-fiverr.svg";
import icon6 from "./icons8-instagram.svg";
import icon7 from "./icons8-linkedin.svg";
import icon8 from "./icons8-medium.svg";
import icon9 from "./icons8-twitter.svg";
import icon10 from "./icons8-whatsapp.svg";

export const behance = icon1;
export const credly = icon2;
export const dribble = icon3;
export const facebook = icon4;
export const fiverr = icon5;
export const instagram = icon6;
export const linkedin = icon7;
export const medium = icon8;
export const twitter = icon9;
export const whatsapp = icon10;
