import icon1 from "./icons8-bootstrap.svg";
import icon2 from "./icons8-chakra-ui.svg";
import icon3 from "./icons8-css3.svg";
import icon4 from "./icons8-eslint.svg";
import icon5 from "./icons8-express-js.svg";
import icon6 from "./icons8-git.svg";
import icon7 from "./icons8-html-5.svg";
import icon8 from "./icons8-javascript.svg";
import icon9 from "./icons8-mongodb.svg";
import icon10 from "./icons8-mongoose.svg";
import icon11 from "./icons8-mysql.svg";
import icon12 from "./icons8-next-js.svg";
import icon13 from "./icons8-node-js.svg";
import icon14 from "./icons8-postgresql.svg";
import icon15 from "./icons8-react.svg";
import icon16 from "./icons8-sass.svg";
import icon17 from "./icons8-tailwind.svg";
import icon18 from "./icons8-typescript.svg";
import icon19 from "./icons8-vite.svg";
import icon20 from "./sequelize-svgrepo-com.svg";
import icon21 from "./mantine-logo.svg";

export const bootstrap = icon1;
export const chakraui = icon2;
export const css3 = icon3;
export const eslint = icon4;
export const expressjs = icon5;
export const git = icon6;
export const html5 = icon7;
export const javascript = icon8;
export const mongodb = icon9;
export const mongoose = icon10;
export const mysql = icon11;
export const nextjs = icon12;
export const nodejs = icon13;
export const postgresql = icon14;
export const react = icon15;
export const sass = icon16;
export const tailwind = icon17;
export const typescript = icon18;
export const vite = icon19;
export const sequelize = icon20;
export const mantine = icon21;
